// generateCode.js
// ===============
// Returns standard JavaScript generated by Escodegen

define([
  'errorMsgs'
], function(
  errorMsgs
) {
  return function generateCode(ast) {
    var amdclean = this,
      options = amdclean.options,
      escodegenOptions = options.escodegen || {};

    if (!_.isPlainObject(escodegen) || !_.isFunction(escodegen.generate)) {
      throw new Error(errorMsgs.escodegen);
    }

    return escodegen.generate(ast, escodegenOptions);
  };
});